services:
  postgres:
    image: postgres:16-alpine
    container_name: ceos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ceos
      POSTGRES_USER: ceos
      POSTGRES_PASSWORD: ceos
    ports:
      - "0.0.0.0:5432:5432" # Fuerza a escuchar en todas las IPs locales
    volumes:
      - ceos_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ceos -d ceos" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ceos_pg_data:
